### ISSUE TITLE
Not compatible with urllib3 2.0

### ISSUE THREAD

**Issue by dgilman** [edgi-govdata-archiving/wayback#116]

**Comment by Mr0grog** [comment]
Ah, yeah, at the very least, this fix for gzip encoding problems in Wayback will need to be removed or done in a different way for v2: https://github.com/edgi-govdata-archiving/wayback/blob/6d360e92c81373fd0476fbbf5ac7961bd8ec7725/wayback/_client.py#L260-L289

I had thought we set constraints for urllib3 v1.x, but it looks like we didn’t, which is causing your test failures on #117. Thanks for calling this out.

I think the first thing that needs doing here is constraining the dependency to `urllib3 >=1.20 <2` as a quick fix, and then we need to fix the above issue in order to be compatible with v2 (or switch to httpx, see #58).

**Comment by Mr0grog** [comment]
Released v0.4.2 with correct dependency constraints.
