### ISSUE TITLE
Is there any way to get the total count of items indexed between two dates that contains a given string (without interating through each item)?

### ISSUE THREAD

**Issue by josh-ashkinaze** [edgi-govdata-archiving/wayback#165]
Hello, 

First off, thank you developers for making such an awesome repo! This is really helpful and the Sphinx docs are great. 

My question: I was wondering if there is some kind of way to get the total count of how many items contain the string S between dates D1 and D2, without actually downloading each item. 

My use case is wanting to count the frequencies of different strings over time on the Internet. But it feels somewhat inefficient to fetch each memento and check if it contains that string. 

However, from the docs I am not so hopeful this can be done :(

**Comment by Mr0grog** [comment]
Last note before closing this:

> My use case is wanting to count the frequencies of different strings over time on the Internet.

If you are interested in *the internet at large* rather than specific sites or URLs, you should check out [Common Crawl](https://commoncrawl.org). The Internet Archive can be pretty idiosyncratic in what gets saved at various points in time, while Common Crawl is intentionally built to try and create something that’s more like a random (or at least broad) sample of the whole internet at specific points in time. It might be much better suited to what you are trying to measure.
