### ISSUE TITLE
Wrap result from `get_memento` in a custom object

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/wayback#2]
Rather than exposing `requests.Response` directly, we could wrap it in a custom object to give us the freedom to refactor in the future. From https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/477

**Comment by Mr0grog** [comment]
In Web Monitoring, we are adding better media type parsing (see edgi-govdata-archiving/web-monitoring-processing#621), and that should probably ultimately live here instead. I’m thinking we’d have:

```python
class MediaType:
    type: str        # e.g. 'text'
    subtype: str     # e.g. 'html'
    parameters: str  # e.g. {'charset', 'utf-8'}

    @property
    def media(self):
        "The main media type without parameters, e.g. 'text/html'"
        return f'{self.type}/{self.subtype}'

	@property
    def parameter_string(self):
        "The parameters as a single string, e.g. 'charset=utf-8; other-param=whatever'"
        return '; '.join(f'{key}={value}' for key, value in self.parameters)

    def __str__(self):
        if parameters:
            return f'{self.media}; {self.parameter_string}'
        else:
            return self.media
```

And then `Memento.media` would be an instance of the above.

**Comment by Mr0grog** [comment]
Or it could be simpler, with just:

```python
memento.media_type == 'text/html'
memento.media_parameters == {'charset': 'utf-8'}
```

**Comment by Mr0grog** [comment]
OK, thinking through an ideal model for a Memento, here’s my first cut:

- `encoding` The text encoding of the response. (Do we need an [`apparent_encoding` like Requests has](https://requests.readthedocs.io/en/latest/api/#requests.Response.apparent_encoding) that detects the encoding if one isn’t specified in the headers?)

- `content` The content of the response in bytes.

- `text` The decoded content of the response as a string.

- `headers` The *archived* headers of the response (that is, the headers that came with the original snapshot, not including additional Wayback headers).

- `history` A list of mementos for any *historical* redirects that led to this memento.

- `debug_history` A list of URLs for any redirects (including those that are involved in general communication with the Wayback Machine, not just historical redirects). (Should this be a bunch of response objects of some sort instead? Memento objects that aren’t actually mementos?)

- `is_redirect` Whether the memento is of a redirect (i.e. had a 3xx status code).

- `ok` Whether the status code was < 400.

- `status_code` The status code of the response as an integer.

- `memento_type` The type of memento (see also #15), e.g. `'raw'`, `'view'`, etc. (Maybe simpler if these are the actual codes the Wayback Machine uses, i.e. `''`, `'id'`, `'im'`, `'js'`, `'cs'`? [See http://archive-access.sourceforge.net/projects/wayback/administrator_manual.html#Archival_URL_Replay_Mode])

- `timestamp` (or `time`?) The timestamp of when the memento was captured, as a `datetime` instance with a timezone (always UTC).

- `url` The original URL that this is a memento of, e.g. `http://epa.gov`, not `http://web.archive.org/web/20200101000000/http://epa.gov`. (Mainly useful when there were redirects.)

- `memento_url` The URL from which this memento was retrieved — basically the opposite of `url` above. I.e. `http://web.archive.org/web/20200101000000/http://epa.gov`, not `http://epa.gov`. (This is mainly a convenience, since you could compose it from `url` + `timestamp` + `memento_type`.)

- `media` Parsed media type information from the `Content-Type` header (see [above comment](https://github.com/edgi-govdata-archiving/wayback/issues/2#issuecomment-682406485)).

- `related` An object with the URLs of related mementos (parsed from the `Link` header):
    - `original`
    - `previous`
    - `next`
    - `last`
    - `timemap`
    - `timegate`

    Could also be `links`? Might be confusing vs. a parsed version of the `Links` header from the original capture, rather than Wayback-related info.

- `close()` Closes the HTTP response. Happens automatically if you read `text` or `content`. Always safe to call (it’s no-op if already closed).
